create table BOOK (
        num_of_publish integer not null,
        date_of_publish timestamp(6),
        id bigint generated by default as identity,
        publisher_id bigint,
        summary varchar(255),
        title varchar(255),
        type varchar(255),
        primary key (id)
    )
--    alter table if exists book
--           add constraint FKgtvt7p649s4x80y6f4842pnfq
--           foreign key (publisher_id)
--           references publisher
